[package]
name = "druid-ha"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
[dependencies]
druid-core = { path = "../druid-core" }
druid-pool = { path = "../druid-pool" }
tokio = { workspace = true, features = ["sync", "time", "rt"] }
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
