[package]
name = "druid-console"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
druid-core = { path = "../druid-core" }
druid-stat = { path = "../druid-stat" }
axum.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
