[package]
name = "druid-util"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
druid-core = { path = "../druid-core" }
chrono.workspace = true
serde.workspace = true
rand.workspace = true
aes-gcm.workspace = true
zeroize.workspace = true
tracing.workspace = true
