use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Select,
    Insert,
    Update,
    Delete,
    From,
    Where,
    And,
    Or,
    Not,
    Join,
    Inner,
    Left,
    Right,
    Outer,
    Cross,
    Full,
    On,
    Group,
    By,
    Having,
    Order,
    Asc,
    Desc,
    Limit,
    Offset,
    Create,
    Alter,
    Drop,
    Table,
    Index,
    View,
    Trigger,
    Set,
    Into,
    Values,
    Default,
    Null,
    Is,
    Like,
    Between,
    In,
    Exists,
    Any,
    All,
    Some,
    Case,
    When,
    Then,
    Else,
    End,
    As,
    Distinct,
    Union,
    Except,
    Intersect,
    AllKeyword,
    Begin,
    Commit,
    Rollback,
    Transaction,
    Start,
    Primary,
    Key,
    Foreign,
    References,
    Constraint,
    Unique,
    Check,
    Cascade,
    Restrict,
    Action,
    No,
    If,
    Replace,
    Merge,
    Using,
    Returning,
    Grant,
    Revoke,
    OnKeyword,
    To,
    Explain,
    Analyze,
    Verbose,
    With,
    Recursive,
    Truncate,
    NotNull,
    Count,
    Int,
    BigInt,
    SmallInt,
    TinyInt,
    VarChar,
    Char,
    Text,
    Boolean,
    Float,
    Double,
    Decimal,
    Numeric,
    Real,
    Date,
    Time,
    Timestamp,
    Blob,
    Clob,
    Json,
    Jsonb,
    Xml,
    Uuid,
    Bytea,
    Ident(String),
    QuotedIdent(String),
    Number(String),
    StringLit(String),
    HexString(String),
    NationalString(String),
    Placeholder,
    Eq,
    Neq,
    Lt,
    Gt,
    Leq,
    Geq,
    Plus,
    Minus,
    Mul,
    Div,
    Mod,
    Dot,
    Comma,
    Semicolon,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Arrow,
    DoubleColon,
    Assign,
    Concat,
    Eof,
    Whitespace,
    Comment(String),
    BlockComment(String),
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Token::Ident(s) => write!(f, "{}", s),
            Token::QuotedIdent(s) => write!(f, "\"{}\"", s),
            Token::Number(n) => write!(f, "{}", n),
            Token::StringLit(s) => write!(f, "'{}'", s),
            Token::Placeholder => write!(f, "?"),
            Token::Eq => write!(f, "="),
            Token::Neq => write!(f, "<>"),
            Token::Lt => write!(f, "<"),
            Token::Gt => write!(f, ">"),
            Token::Leq => write!(f, "<="),
            Token::Geq => write!(f, ">="),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Mul => write!(f, "*"),
            Token::Div => write!(f, "/"),
            Token::Concat => write!(f, "||"),
            Token::Dot => write!(f, "."),
            Token::Comma => write!(f, ","),
            Token::Semicolon => write!(f, ";"),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::Eof => write!(f, "<EOF>"),
            _ => write!(f, "{}", format!("{:?}", self).to_uppercase()),
        }
    }
}

pub fn lookup_keyword(word: &str) -> Option<Token> {
    Some(match word.to_ascii_lowercase().as_str() {
        "select" => Token::Select,
        "insert" => Token::Insert,
        "update" => Token::Update,
        "delete" => Token::Delete,
        "from" => Token::From,
        "where" => Token::Where,
        "and" => Token::And,
        "or" => Token::Or,
        "not" => Token::Not,
        "join" => Token::Join,
        "inner" => Token::Inner,
        "left" => Token::Left,
        "right" => Token::Right,
        "outer" => Token::Outer,
        "cross" => Token::Cross,
        "full" => Token::Full,
        "on" => Token::On,
        "group" => Token::Group,
        "by" => Token::By,
        "having" => Token::Having,
        "order" => Token::Order,
        "asc" => Token::Asc,
        "desc" => Token::Desc,
        "limit" => Token::Limit,
        "offset" => Token::Offset,
        "create" => Token::Create,
        "alter" => Token::Alter,
        "drop" => Token::Drop,
        "table" => Token::Table,
        "index" => Token::Index,
        "view" => Token::View,
        "trigger" => Token::Trigger,
        "set" => Token::Set,
        "into" => Token::Into,
        "values" => Token::Values,
        "default" => Token::Default,
        "null" => Token::Null,
        "is" => Token::Is,
        "like" => Token::Like,
        "between" => Token::Between,
        "in" => Token::In,
        "exists" => Token::Exists,
        "any" => Token::Any,
        "all" => Token::All,
        "some" => Token::Some,
        "case" => Token::Case,
        "when" => Token::When,
        "then" => Token::Then,
        "else" => Token::Else,
        "end" => Token::End,
        "as" => Token::As,
        "distinct" => Token::Distinct,
        "union" => Token::Union,
        "except" => Token::Except,
        "intersect" => Token::Intersect,
        "begin" => Token::Begin,
        "commit" => Token::Commit,
        "rollback" => Token::Rollback,
        "transaction" => Token::Transaction,
        "start" => Token::Start,
        "primary" => Token::Primary,
        "key" => Token::Key,
        "foreign" => Token::Foreign,
        "references" => Token::References,
        "constraint" => Token::Constraint,
        "unique" => Token::Unique,
        "check" => Token::Check,
        "cascade" => Token::Cascade,
        "restrict" => Token::Restrict,
        "no" => Token::No,
        "action" => Token::Action,
        "if" => Token::If,
        "replace" => Token::Replace,
        "merge" => Token::Merge,
        "using" => Token::Using,
        "returning" => Token::Returning,
        "grant" => Token::Grant,
        "revoke" => Token::Revoke,
        "explain" => Token::Explain,
        "analyze" => Token::Analyze,
        "verbose" => Token::Verbose,
        "with" => Token::With,
        "recursive" => Token::Recursive,
        "truncate" => Token::Truncate,
        "int" | "integer" => Token::Int,
        "bigint" => Token::BigInt,
        "smallint" => Token::SmallInt,
        "tinyint" => Token::TinyInt,
        "varchar" => Token::VarChar,
        "char" | "character" => Token::Char,
        "text" => Token::Text,
        "boolean" | "bool" => Token::Boolean,
        "float" => Token::Float,
        "double" => Token::Double,
        "decimal" | "numeric" | "number" => Token::Decimal,
        "real" => Token::Real,
        "date" => Token::Date,
        "time" => Token::Time,
        "timestamp" => Token::Timestamp,
        "blob" => Token::Blob,
        "clob" => Token::Clob,
        "json" => Token::Json,
        "jsonb" => Token::Jsonb,
        "xml" => Token::Xml,
        "uuid" => Token::Uuid,
        "bytea" => Token::Bytea,
        "count" => Token::Count,
        _ => return None,
    })
}
