use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Select,
    Insert,
    Update,
    Delete,
    From,
    Where,
    And,
    Or,
    Not,
    Join,
    Inner,
    Left,
    Right,
    Outer,
    Cross,
    Full,
    On,
    Group,
    By,
    Having,
    Order,
    Asc,
    Desc,
    Limit,
    Offset,
    Create,
    Alter,
    Drop,
    Table,
    Index,
    View,
    Trigger,
    Set,
    Into,
    Values,
    Default,
    Null,
    Is,
    Like,
    Between,
    In,
    Exists,
    Any,
    All,
    Some,
    Case,
    When,
    Then,
    Else,
    End,
    As,
    Distinct,
    Union,
    Except,
    Intersect,
    AllKeyword,
    Begin,
    Commit,
    Rollback,
    Transaction,
    Start,
    Primary,
    Key,
    Foreign,
    References,
    Constraint,
    Unique,
    Check,
    Cascade,
    Restrict,
    Action,
    No,
    If,
    Replace,
    Merge,
    Using,
    Returning,
    Grant,
    Revoke,
    OnKeyword,
    To,
    Explain,
    Analyze,
    Verbose,
    With,
    Recursive,
    Truncate,
    NotNull,
    Count,
    Int,
    BigInt,
    SmallInt,
    TinyInt,
    VarChar,
    Char,
    Text,
    Boolean,
    Float,
    Double,
    Decimal,
    Numeric,
    Real,
    Date,
    Time,
    Timestamp,
    Blob,
    Clob,
    Json,
    Jsonb,
    Xml,
    Uuid,
    Bytea,
    Ident(String),
    QuotedIdent(String),
    Number(String),
    StringLit(String),
    HexString(String),
    NationalString(String),
    Placeholder,
    Eq,
    Neq,
    Lt,
    Gt,
    Leq,
    Geq,
    Plus,
    Minus,
    Mul,
    Div,
    Mod,
    Dot,
    Comma,
    Semicolon,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Arrow,
    DoubleColon,
    Assign,
    Eof,
    Whitespace,
    Comment(String),
    BlockComment(String),
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Token::Ident(s) => write!(f, "{}", s),
            Token::QuotedIdent(s) => write!(f, "\"{}\"", s),
            Token::Number(n) => write!(f, "{}", n),
            Token::StringLit(s) => write!(f, "'{}'", s),
            Token::Placeholder => write!(f, "?"),
            Token::Eq => write!(f, "="),
            Token::Neq => write!(f, "<>"),
            Token::Lt => write!(f, "<"),
            Token::Gt => write!(f, ">"),
            Token::Leq => write!(f, "<="),
            Token::Geq => write!(f, ">="),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Mul => write!(f, "*"),
            Token::Div => write!(f, "/"),
            Token::Dot => write!(f, "."),
            Token::Comma => write!(f, ","),
            Token::Semicolon => write!(f, ";"),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::Eof => write!(f, "<EOF>"),
            _ => write!(f, "{}", format!("{:?}", self).to_uppercase()),
        }
    }
}

pub fn lookup_keyword(word: &str) -> Option<Token> {
    Some(match word.to_uppercase().as_str() {
        "SELECT" => Token::Select,
        "INSERT" => Token::Insert,
        "UPDATE" => Token::Update,
        "DELETE" => Token::Delete,
        "FROM" => Token::From,
        "WHERE" => Token::Where,
        "AND" => Token::And,
        "OR" => Token::Or,
        "NOT" => Token::Not,
        "JOIN" => Token::Join,
        "INNER" => Token::Inner,
        "LEFT" => Token::Left,
        "RIGHT" => Token::Right,
        "OUTER" => Token::Outer,
        "CROSS" => Token::Cross,
        "FULL" => Token::Full,
        "ON" => Token::On,
        "GROUP" => Token::Group,
        "BY" => Token::By,
        "HAVING" => Token::Having,
        "ORDER" => Token::Order,
        "ASC" => Token::Asc,
        "DESC" => Token::Desc,
        "LIMIT" => Token::Limit,
        "OFFSET" => Token::Offset,
        "CREATE" => Token::Create,
        "ALTER" => Token::Alter,
        "DROP" => Token::Drop,
        "TABLE" => Token::Table,
        "INDEX" => Token::Index,
        "VIEW" => Token::View,
        "TRIGGER" => Token::Trigger,
        "SET" => Token::Set,
        "INTO" => Token::Into,
        "VALUES" => Token::Values,
        "DEFAULT" => Token::Default,
        "NULL" => Token::Null,
        "IS" => Token::Is,
        "LIKE" => Token::Like,
        "BETWEEN" => Token::Between,
        "IN" => Token::In,
        "EXISTS" => Token::Exists,
        "ANY" => Token::Any,
        "ALL" => Token::All,
        "SOME" => Token::Some,
        "CASE" => Token::Case,
        "WHEN" => Token::When,
        "THEN" => Token::Then,
        "ELSE" => Token::Else,
        "END" => Token::End,
        "AS" => Token::As,
        "DISTINCT" => Token::Distinct,
        "UNION" => Token::Union,
        "EXCEPT" => Token::Except,
        "INTERSECT" => Token::Intersect,
        "BEGIN" => Token::Begin,
        "COMMIT" => Token::Commit,
        "ROLLBACK" => Token::Rollback,
        "TRANSACTION" => Token::Transaction,
        "START" => Token::Start,
        "PRIMARY" => Token::Primary,
        "KEY" => Token::Key,
        "FOREIGN" => Token::Foreign,
        "REFERENCES" => Token::References,
        "CONSTRAINT" => Token::Constraint,
        "UNIQUE" => Token::Unique,
        "CHECK" => Token::Check,
        "CASCADE" => Token::Cascade,
        "RESTRICT" => Token::Restrict,
        "NO" => Token::No,
        "ACTION" => Token::Action,
        "IF" => Token::If,
        "REPLACE" => Token::Replace,
        "MERGE" => Token::Merge,
        "USING" => Token::Using,
        "RETURNING" => Token::Returning,
        "GRANT" => Token::Grant,
        "REVOKE" => Token::Revoke,
        "EXPLAIN" => Token::Explain,
        "ANALYZE" => Token::Analyze,
        "VERBOSE" => Token::Verbose,
        "WITH" => Token::With,
        "RECURSIVE" => Token::Recursive,
        "TRUNCATE" => Token::Truncate,
        "INT" | "INTEGER" => Token::Int,
        "BIGINT" => Token::BigInt,
        "SMALLINT" => Token::SmallInt,
        "TINYINT" => Token::TinyInt,
        "VARCHAR" => Token::VarChar,
        "CHAR" | "CHARACTER" => Token::Char,
        "TEXT" => Token::Text,
        "BOOLEAN" | "BOOL" => Token::Boolean,
        "FLOAT" => Token::Float,
        "DOUBLE" => Token::Double,
        "DECIMAL" | "NUMERIC" | "NUMBER" => Token::Decimal,
        "REAL" => Token::Real,
        "DATE" => Token::Date,
        "TIME" => Token::Time,
        "TIMESTAMP" => Token::Timestamp,
        "BLOB" => Token::Blob,
        "CLOB" => Token::Clob,
        "JSON" => Token::Json,
        "JSONB" => Token::Jsonb,
        "XML" => Token::Xml,
        "UUID" => Token::Uuid,
        "BYTEA" => Token::Bytea,
        "COUNT" => Token::Count,
        _ => return None,
    })
}
